/**
 * Composer Scene data model.
 *
 * Pure, JSON-serialisable type definitions for the unified composer canvas
 * feature. This module owns the **shapes** only — it does not own affine math
 * (`compose.ts`), gesture math (`gestures.ts`), reactive state
 * (`scene_store.ts`), persistence (`persistence.ts`), or rendering
 * (`ui/composer/*`).
 *
 * Every exported type is JSON-serialisable: no `Date`, no `Map`, no `Set`,
 * no functions, no class instances. A `Scene` value can be round-tripped
 * through `JSON.stringify` / `JSON.parse` without loss (Req 10.3, 14.1, 14.4).
 *
 * Z-order convention (Req 1.3, 9.1): `items[0]` is the bottommost item
 * (drawn first / behind); `items[items.length - 1]` is the topmost (drawn
 * last / in front). The Items List panel displays this array reversed so the
 * topmost item appears at the top of the panel (Req 17.1).
 *
 * @see .kiro/specs/unified-composer-canvas/design.md §"Components and Interfaces" #1
 * @see Requirements 9.1, 10.3, 14.1, 14.4
 */

import type { Polyline } from '../types';

// -----------------------------------------------------------------------------
// Identifiers
// -----------------------------------------------------------------------------

/**
 * Stable opaque item identifier. ULID-style string (lexicographically
 * sortable, monotonically generated). Generated by the SceneStore on
 * `addItem`; consumers MUST treat it as opaque.
 */
export type ItemId = string;

// -----------------------------------------------------------------------------
// Transform
// -----------------------------------------------------------------------------

/**
 * Per-item affine transform applied to the item's local-frame polylines at
 * composition time.
 *
 * The mapping is `T(p) = R(rotationRad) · S(sx, sy) · p + (x, y)`,
 * expanded to:
 *
 *     out.x = cos(θ)·sx·p.x − sin(θ)·sy·p.y + x
 *     out.y = sin(θ)·sx·p.x + cos(θ)·sy·p.y + y
 *
 * Invariants enforced by the SceneStore on every commit:
 *   - `|sx| ≥ SCALE_MIN ∧ |sy| ≥ SCALE_MIN` (Req 5.4)
 *   - `rotationRad ∈ [0, 2π)` (Req 6.2)
 *
 * @see Requirements 5.4, 6.2, 9.2
 */
export interface Transform {
    /** Translation in scene units. */
    x: number;
    y: number;
    /**
     * Scale factors. Defaults `1, 1`. Invariant after `clampScale`:
     * `|sx| ≥ SCALE_MIN ∧ |sy| ≥ SCALE_MIN` (Req 5.4).
     */
    sx: number;
    sy: number;
    /**
     * Counter-clockwise rotation about the item's local origin, normalised
     * into `[0, 2π)` for storage so equivalent rotations have a single
     * canonical value (Req 6.2).
     */
    rotationRad: number;
}

// -----------------------------------------------------------------------------
// Items
// -----------------------------------------------------------------------------

/**
 * Fields shared by every Item kind. Concrete items extend this with a
 * `kind` discriminator and a `source` metadata payload.
 */
export interface BaseItem {
    id: ItemId;
    transform: Transform;
    /**
     * Local-frame polylines, as produced by the source generator
     * (image vectoriser, text-to-strokes, freehand capture). Untransformed.
     */
    content: Polyline[];
}

/**
 * An item whose content is the `Polyline[]` produced by the existing image
 * vectoriser for an imported image file. `source` metadata is persisted
 * with the snapshot so the item can be restored without re-running the
 * vectoriser (Req 14.4).
 */
export interface Image_Item extends BaseItem {
    kind: 'image';
    source: { filename: string; sizeBytes: number };
}

/**
 * An item whose content is the `Polyline[]` produced by the existing
 * text-to-strokes generator for the entered string and font/size settings.
 */
export interface Text_Item extends BaseItem {
    kind: 'text';
    source: {
        text: string;
        fontName: string;
        fontSizeMm: number;
        letterSpacingPct: number;
    };
}

/**
 * An item whose content is the `Polyline[]` captured by the existing
 * freehand stroke recorder.
 */
export interface Freehand_Item extends BaseItem {
    kind: 'freehand';
    source: { capturedAtMs: number };
}

/**
 * Discriminated union over the three Item kinds. The `kind` tag is the
 * discriminator; pattern-match on it before reading kind-specific fields.
 */
export type Item = Image_Item | Text_Item | Freehand_Item;

// -----------------------------------------------------------------------------
// Scene
// -----------------------------------------------------------------------------

/**
 * The Composer Scene — single source of truth for what will be drawn next.
 *
 * `items[0]` is bottommost (drawn first / behind); `items[items.length - 1]`
 * is topmost (drawn last / in front). The Items List displays this array
 * reversed so the topmost item appears at the top of the panel (Req 17.1).
 *
 * `schemaVersion` is the literal `1` — this is the on-disk format version
 * for the localStorage snapshot (Req 14.1, 14.4). Mismatched versions are
 * treated as malformed by `parseScene` (Req 14.3).
 *
 * `selectedId` is `null` when no item is selected (Req 3.4).
 */
export interface Scene {
    schemaVersion: 1;
    items: Item[];
    selectedId: ItemId | null;
}

// -----------------------------------------------------------------------------
// Constructors / constants
// -----------------------------------------------------------------------------

/**
 * Build a fresh identity Transform: zero translation, unit scale, zero
 * rotation. Returns a new object on every call so callers can mutate it
 * freely (the Transform shape is plain data).
 */
export function makeIdentityTransform(): Transform {
    return { x: 0, y: 0, sx: 1, sy: 1, rotationRad: 0 };
}

/**
 * The empty Composer Scene used as the boot-time default and after `clear()`.
 *
 * Frozen so accidental mutation of the singleton triggers a TypeError in
 * strict mode rather than silently corrupting the boot state. Mutators in
 * `scene_store.ts` always allocate fresh Scene objects, so the freeze is a
 * defensive guard, not a hot-path concern.
 */
export const EMPTY_SCENE: Scene = Object.freeze({
    schemaVersion: 1 as const,
    items: Object.freeze([] as Item[]) as unknown as Item[],
    selectedId: null,
}) as Scene;
